spring.application.name=ShopUser
jwt.private-key=${JWT_PRIVATE_KEY}
jwt.public-key=${JWT_PUBLIC_KEY}
#Databaskonfiguration
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3307/shopuser}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:${DB_USERNAME}}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:${DB_PASSWORD}}
spring.jpa.hibernate.ddl-auto=none
#ProductService
product-service.url=${PRODUCT_SERVICE_URL:http://localhost:8081}
